/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class bool_t {
   public static final int MAV_FALSE = 1; /*  | */
   public static final int MAV_TRUE = 2; /*  | */
   public static final int bool_t_ENUM_END = 3; /*  | */
}
            