/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class cmd_t {
   public static final int CMD_SAVE = 1; /*  | */
   public static final int CMD_LOAD = 2; /*  | */
   public static final int cmd_t_ENUM_END = 3; /*  | */
}
            