/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class motor_t {
   public static final int DC = 1; /*  | */
   public static final int STEP = 2; /*  | */
   public static final int motor_t_ENUM_END = 3; /*  | */
}
            