/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class motor_type_t {
   public static final int MOTOR_TYPE_UNKNOWN = 1; /*  | */
   public static final int MOTOR_TYPE_DC = 2; /*  | */
   public static final int MOTOR_TYPE_STEP = 3; /*  | */
   public static final int motor_type_t_ENUM_END = 4; /*  | */
}
            