/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class pidc_t {
   public static final int PID_TILT = 1; /*  | */
   public static final int PID_VEL = 2; /*  | */
   public static final int PID_POS = 3; /*  | */
   public static final int PID_WHE0 = 4; /*  | */
   public static final int PID_WHE1 = 5; /*  | */
   public static final int PID_WHE2 = 6; /*  | */
   public static final int PID_WHE3 = 7; /*  | */
   public static final int PID_SYNC = 8; /*  | */
   public static final int pidc_t_ENUM_END = 9; /*  | */
}
            