/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class resond_t {
   public static final int RESPOND_OK = 1; /*  | */
   public static final int RESPOND_ERROR = 2; /*  | */
   public static final int resond_t_ENUM_END = 3; /*  | */
}
            