/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class rmode_t {
   public static final int MODE_RUN = 1; /*  | */
   public static final int MODE_HW = 2; /*  | */
   public static final int MODE_IMU = 3; /*  | */
   public static final int MODE_PIDT_TW = 4; /*  | */
   public static final int MODE_PIDT_TA = 5; /*  | */
   public static final int rmode_t_ENUM_END = 6; /*  | */
}
            