/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class role_t {
   public static final int ANCHOR = 1; /*  | */
   public static final int TAG = 2; /*  | */
   public static final int role_t_ENUM_END = 3; /*  | */
}
            