/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class tilt_type_t {
   public static final int ROLL = 1; /*  | */
   public static final int PITCH = 2; /*  | */
   public static final int tilt_type_t_ENUM_END = 3; /*  | */
}
            