/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.protocol;

import java.util.HashMap;
import java.util.Map;

/**
 * CRC-16/MCRF4XX calculation for MAVlink messages. The checksum must be
 * initialized, updated with which field of the message, and then finished with
 * the message id.
 *
 */
public class CRC {
    private static final Map<Integer, Integer> MAVLINK_MESSAGE_CRCS;
    private static final int CRC_INIT_VALUE = 0xffff;
    private int crcValue;

    static {
        MAVLINK_MESSAGE_CRCS = new HashMap<>();
        MAVLINK_MESSAGE_CRCS.put(0, 164);
        MAVLINK_MESSAGE_CRCS.put(1, 44);
        MAVLINK_MESSAGE_CRCS.put(2, 245);
        MAVLINK_MESSAGE_CRCS.put(3, 202);
        MAVLINK_MESSAGE_CRCS.put(4, 150);
        MAVLINK_MESSAGE_CRCS.put(5, 132);
        MAVLINK_MESSAGE_CRCS.put(6, 93);
        MAVLINK_MESSAGE_CRCS.put(7, 54);
        MAVLINK_MESSAGE_CRCS.put(8, 183);
        MAVLINK_MESSAGE_CRCS.put(9, 75);
        MAVLINK_MESSAGE_CRCS.put(10, 30);
        MAVLINK_MESSAGE_CRCS.put(11, 170);
        MAVLINK_MESSAGE_CRCS.put(12, 8);
        MAVLINK_MESSAGE_CRCS.put(13, 31);
        MAVLINK_MESSAGE_CRCS.put(14, 158);
        MAVLINK_MESSAGE_CRCS.put(15, 22);
        MAVLINK_MESSAGE_CRCS.put(16, 118);
        MAVLINK_MESSAGE_CRCS.put(17, 2);
        MAVLINK_MESSAGE_CRCS.put(18, 198);
        MAVLINK_MESSAGE_CRCS.put(19, 92);
        MAVLINK_MESSAGE_CRCS.put(20, 91);
        MAVLINK_MESSAGE_CRCS.put(21, 35);
        MAVLINK_MESSAGE_CRCS.put(22, 170);
        MAVLINK_MESSAGE_CRCS.put(23, 244);
        MAVLINK_MESSAGE_CRCS.put(24, 59);
        MAVLINK_MESSAGE_CRCS.put(25, 4);
        MAVLINK_MESSAGE_CRCS.put(26, 177);
        MAVLINK_MESSAGE_CRCS.put(27, 71);
        MAVLINK_MESSAGE_CRCS.put(28, 103);
        MAVLINK_MESSAGE_CRCS.put(29, 183);
        MAVLINK_MESSAGE_CRCS.put(30, 72);
        
    }

    /**
     * Accumulate the CRC by adding one char at a time.
     *
     * The checksum function adds the hash of one char at a time to the 16 bit
     * checksum (uint16_t).
     *
     * @param data new char to hash
     **/
    public void update_checksum(int data) {
        data = data & 0xff; //cast because we want an unsigned type
        int tmp = data ^ (crcValue & 0xff);
        tmp ^= (tmp << 4) & 0xff;
        crcValue = ((crcValue >> 8) & 0xff) ^ (tmp << 8) ^ (tmp << 3) ^ ((tmp >> 4) & 0xf);
    }

    /**
     * Finish the CRC calculation of a message, by running the CRC with the
     * Magic Byte.
     *
     * @param msgid The message id number
     * @return boolean True if the checksum was successfully finished. Otherwise false
     */
    public boolean finish_checksum(int msgid) {
        if (MAVLINK_MESSAGE_CRCS.containsKey(msgid)) {
            update_checksum(MAVLINK_MESSAGE_CRCS.get(msgid));
            return true;
        }
        return false;
    }

    /**
     * Initialize the buffer for the CRC16/MCRF4XX
     */
    public void start_checksum() {
        crcValue = CRC_INIT_VALUE;
    }

    public int getMSB() {
        return ((crcValue >> 8) & 0xff);
    }

    public int getLSB() {
        return (crcValue & 0xff);
    }

    public CRC() {
        start_checksum();
    }

}
        