/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BLE_MESH PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * BLE mesh message
 */
public class msg_ble_mesh extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BLE_MESH = 20;
    public static final int MAVLINK_MSG_LENGTH = 4;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BLE_MESH;

      
    /**
     * 
     */
    public int uwb_address;
      
    /**
     * 
     */
    public int mesh_address;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_BLE_MESH;
        
        packet.payload.putUnsignedShort(uwb_address);
        packet.payload.putUnsignedShort(mesh_address);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a ble_mesh message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.uwb_address = payload.getUnsignedShort();
        this.mesh_address = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_ble_mesh() {
        this.msgid = MAVLINK_MSG_ID_BLE_MESH;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_ble_mesh( int uwb_address, int mesh_address) {
        this.msgid = MAVLINK_MSG_ID_BLE_MESH;

        this.uwb_address = uwb_address;
        this.mesh_address = mesh_address;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_ble_mesh( int uwb_address, int mesh_address, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BLE_MESH;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.uwb_address = uwb_address;
        this.mesh_address = mesh_address;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_ble_mesh(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BLE_MESH;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BLE_MESH - sysid:"+sysid+" compid:"+compid+" uwb_address:"+uwb_address+" mesh_address:"+mesh_address+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BLE_MESH";
    }
}
        