/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MOTOR_SPEED PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Set or info speed for motors. To test the hardware and motor rotaion direction. No need a respond message for confimation
*/
public class msg_motor_speed extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MOTOR_SPEED = 7;
    public static final int MAVLINK_MSG_LENGTH = 4;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MOTOR_SPEED;


      
    /**
    * Motor 0 speed
    */
    public short motor_speed_0;
      
    /**
    * Motor 1 Speed
    */
    public short motor_speed_1;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MOTOR_SPEED;
              
        packet.payload.putShort(motor_speed_0);
              
        packet.payload.putShort(motor_speed_1);
        
        return packet;
    }

    /**
    * Decode a motor_speed message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.motor_speed_0 = payload.getShort();
              
        this.motor_speed_1 = payload.getShort();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_motor_speed(){
        msgid = MAVLINK_MSG_ID_MOTOR_SPEED;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_motor_speed(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MOTOR_SPEED;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MOTOR_SPEED - sysid:"+sysid+" compid:"+compid+" motor_speed_0:"+motor_speed_0+" motor_speed_1:"+motor_speed_1+"";
    }
}
        