/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CMD_CHANGE_MODE PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * Command Change Mode. Need a respond message for confimation
 */
public class msg_cmd_change_mode extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_CMD_CHANGE_MODE = 1;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CMD_CHANGE_MODE;

      
    /**
     * Mode
     */
    public short cmd_change_mode;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_CMD_CHANGE_MODE;
        
        packet.payload.putUnsignedByte(cmd_change_mode);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a cmd_change_mode message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.cmd_change_mode = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_cmd_change_mode() {
        this.msgid = MAVLINK_MSG_ID_CMD_CHANGE_MODE;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_cmd_change_mode( short cmd_change_mode) {
        this.msgid = MAVLINK_MSG_ID_CMD_CHANGE_MODE;

        this.cmd_change_mode = cmd_change_mode;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_cmd_change_mode( short cmd_change_mode, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_CMD_CHANGE_MODE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.cmd_change_mode = cmd_change_mode;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_cmd_change_mode(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_CMD_CHANGE_MODE;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_CMD_CHANGE_MODE - sysid:"+sysid+" compid:"+compid+" cmd_change_mode:"+cmd_change_mode+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_CMD_CHANGE_MODE";
    }
}
        