/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE EVT_ACCEL_RAW PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * IMU raw value. No need a respond message for confimation
 */
public class msg_evt_accel_raw extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_EVT_ACCEL_RAW = 11;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_EVT_ACCEL_RAW;

      
    /**
     * Accel X
     */
    public float acc_x;
      
    /**
     * Accel Y
     */
    public float acc_y;
      
    /**
     * Accel Z
     */
    public float acc_z;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_EVT_ACCEL_RAW;
        
        packet.payload.putFloat(acc_x);
        packet.payload.putFloat(acc_y);
        packet.payload.putFloat(acc_z);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a evt_accel_raw message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.acc_x = payload.getFloat();
        this.acc_y = payload.getFloat();
        this.acc_z = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_evt_accel_raw() {
        this.msgid = MAVLINK_MSG_ID_EVT_ACCEL_RAW;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_evt_accel_raw( float acc_x, float acc_y, float acc_z) {
        this.msgid = MAVLINK_MSG_ID_EVT_ACCEL_RAW;

        this.acc_x = acc_x;
        this.acc_y = acc_y;
        this.acc_z = acc_z;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_evt_accel_raw( float acc_x, float acc_y, float acc_z, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_EVT_ACCEL_RAW;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.acc_x = acc_x;
        this.acc_y = acc_y;
        this.acc_z = acc_z;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_evt_accel_raw(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_EVT_ACCEL_RAW;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_EVT_ACCEL_RAW - sysid:"+sysid+" compid:"+compid+" acc_x:"+acc_x+" acc_y:"+acc_y+" acc_z:"+acc_z+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_EVT_ACCEL_RAW";
    }
}
        