/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE DISTANCE PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * Distance message
 */
public class msg_distance extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_DISTANCE = 24;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_DISTANCE;

      
    /**
     * 
     */
    public float distance;
      
    /**
     * 
     */
    public int uwb_address;
      
    /**
     * 
     */
    public int anchor;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_DISTANCE;
        
        packet.payload.putFloat(distance);
        packet.payload.putUnsignedShort(uwb_address);
        packet.payload.putUnsignedShort(anchor);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a distance message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.distance = payload.getFloat();
        this.uwb_address = payload.getUnsignedShort();
        this.anchor = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_distance() {
        this.msgid = MAVLINK_MSG_ID_DISTANCE;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_distance( float distance, int uwb_address, int anchor) {
        this.msgid = MAVLINK_MSG_ID_DISTANCE;

        this.distance = distance;
        this.uwb_address = uwb_address;
        this.anchor = anchor;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_distance( float distance, int uwb_address, int anchor, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_DISTANCE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.distance = distance;
        this.uwb_address = uwb_address;
        this.anchor = anchor;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_distance(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_DISTANCE;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_DISTANCE - sysid:"+sysid+" compid:"+compid+" distance:"+distance+" uwb_address:"+uwb_address+" anchor:"+anchor+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_DISTANCE";
    }
}
        