/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MOTOR_SPEED_STEP PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * 
 */
public class msg_motor_speed_step extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MOTOR_SPEED_STEP = 8;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;

      
    /**
     * Motor 0 speed
     */
    public float motor_0;
      
    /**
     * Motor 1 Speed
     */
    public float motor_1;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;
        
        packet.payload.putFloat(motor_0);
        packet.payload.putFloat(motor_1);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a motor_speed_step message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.motor_0 = payload.getFloat();
        this.motor_1 = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_motor_speed_step() {
        this.msgid = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_motor_speed_step( float motor_0, float motor_1) {
        this.msgid = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;

        this.motor_0 = motor_0;
        this.motor_1 = motor_1;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_motor_speed_step( float motor_0, float motor_1, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.motor_0 = motor_0;
        this.motor_1 = motor_1;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_motor_speed_step(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MOTOR_SPEED_STEP;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MOTOR_SPEED_STEP - sysid:"+sysid+" compid:"+compid+" motor_0:"+motor_0+" motor_1:"+motor_1+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MOTOR_SPEED_STEP";
    }
}
        