/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MEASUREMENT PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * Measurement message
 */
public class msg_measurement extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MEASUREMENT = 29;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MEASUREMENT;

      
    /**
     * 
     */
    public float rx;
      
    /**
     * 
     */
    public float ry;
      
    /**
     * 
     */
    public float range;
      
    /**
     * 
     */
    public float yaw;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MEASUREMENT;
        
        packet.payload.putFloat(rx);
        packet.payload.putFloat(ry);
        packet.payload.putFloat(range);
        packet.payload.putFloat(yaw);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a measurement message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.rx = payload.getFloat();
        this.ry = payload.getFloat();
        this.range = payload.getFloat();
        this.yaw = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_measurement() {
        this.msgid = MAVLINK_MSG_ID_MEASUREMENT;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_measurement( float rx, float ry, float range, float yaw) {
        this.msgid = MAVLINK_MSG_ID_MEASUREMENT;

        this.rx = rx;
        this.ry = ry;
        this.range = range;
        this.yaw = yaw;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_measurement( float rx, float ry, float range, float yaw, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MEASUREMENT;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.rx = rx;
        this.ry = ry;
        this.range = range;
        this.yaw = yaw;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_measurement(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MEASUREMENT;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MEASUREMENT - sysid:"+sysid+" compid:"+compid+" rx:"+rx+" ry:"+ry+" range:"+range+" yaw:"+yaw+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MEASUREMENT";
    }
}
        