/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TOF PACKING
package com.MAVLink.protocol;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * TOF message
 */
public class msg_tof extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TOF = 24;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TOF;

      
    /**
     * 
     */
    public long tof;
      
    /**
     * 
     */
    public int uwb_address;
      
    /**
     * 
     */
    public int anchor;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_TOF;
        
        packet.payload.putUnsignedInt(tof);
        packet.payload.putUnsignedShort(uwb_address);
        packet.payload.putUnsignedShort(anchor);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a tof message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.tof = payload.getUnsignedInt();
        this.uwb_address = payload.getUnsignedShort();
        this.anchor = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_tof() {
        this.msgid = MAVLINK_MSG_ID_TOF;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_tof( long tof, int uwb_address, int anchor) {
        this.msgid = MAVLINK_MSG_ID_TOF;

        this.tof = tof;
        this.uwb_address = uwb_address;
        this.anchor = anchor;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_tof( long tof, int uwb_address, int anchor, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TOF;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.tof = tof;
        this.uwb_address = uwb_address;
        this.anchor = anchor;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_tof(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TOF;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TOF - sysid:"+sysid+" compid:"+compid+" tof:"+tof+" uwb_address:"+uwb_address+" anchor:"+anchor+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TOF";
    }
}
        